### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by CoFix** [milabs/drop-tcp-sock#2]
Hello milabs,

I am trying install your module. I am not linux guru.
This is my commands

> cd 
git clone https://github.com/milabs/drop-tcp-sock.git
cd drop*
make
insmod ./drop-tcp-sock.ko

> 

I am getting this error.

make -C /lib/modules/4.15.0-29-generic/build M=$PWD
make[1]: *** /lib/modules/4.15.0-29-generic/build: No such file or directory.  Stop.
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 2

What can i do?

Thank You.

**Comment by milabs** [comment]
Hey, it seems that you have not installed linux kernel headers?

**Comment by CoFix** [comment]
I dont know how can i install it?

Can you give me commands please?

**Comment by milabs** [comment]
What Linux distro are you using?

**Comment by CoFix** [comment]
Ubuntu 18

**Comment by milabs** [comment]
Try `sudo apt install linux-headers-$(uname -r)`.

**Comment by CoFix** [comment]
Thank you

**Comment by CoFix** [comment]
How can i add port range?
For example:
My destination: 1.2.3.4:17250
Other ip: 5.4.3.2:port is changing all time

echo "1.2.3.4:17250 5.4.3.2:what can i put here?" >/proc/net/tcpdropsock

**Comment by milabs** [comment]
It's not possible to use port range. See [usage](https://github.com/milabs/drop-tcp-sock/blob/master/README.md) for details.

**Comment by CoFix** [comment]
Do I have to type each port line by line?

echo "1.2.3.4:17250 5.4.3.2:60000?" >/proc/net/tcpdropsock
echo "1.2.3.4:17250 5.4.3.2:60001?" >/proc/net/tcpdropsock
echo "1.2.3.4:17250 5.4.3.2:60002?" >/proc/net/tcpdropsock
.
.
??

**Comment by milabs** [comment]
Correct. Line-by-line or multiple lines at once (batching).
