### ISSUE TITLE
Usage is missing netstat -t switch

### ISSUE THREAD

**Issue by vspin** [milabs/drop-tcp-sock#7]
The following usage is missing the netstat -t switch:

netstat -n | grep WAIT | awk '{print $4"\t"$5}'

Should be:

netstat -t -n | grep WAIT | awk '{print $4"\t"$5}'

**Comment by milabs** [comment]
Can't see the difference on CentOS 7:
```
[root@localhost ~]# netstat -n | grep WAIT | awk '{print $4"\t"$5}'
10.0.2.15:33014	185.224.16.132:443
10.0.2.15:45740	185.126.112.9:80
10.0.2.15:38900	188.246.224.67:80
10.0.2.15:33022	185.224.16.132:443
10.0.2.15:38916	188.246.224.67:80
10.0.2.15:33018	185.224.16.132:443
10.0.2.15:45734	185.126.112.9:80
10.0.2.15:38918	188.246.224.67:80
[root@localhost ~]# netstat -nt | grep WAIT | awk '{print $4"\t"$5}'
10.0.2.15:33014	185.224.16.132:443
10.0.2.15:45740	185.126.112.9:80
10.0.2.15:38900	188.246.224.67:80
10.0.2.15:33022	185.224.16.132:443
10.0.2.15:38916	188.246.224.67:80
10.0.2.15:33018	185.224.16.132:443
10.0.2.15:45734	185.126.112.9:80
10.0.2.15:38918	188.246.224.67:80
```

**Comment by tbarbette** [comment]
Without -n netstat will try to resolve domain names indeed so you won't have the IPs. I'm not sure exactly when it does it though. It will translate all the ones in /etc/hosts at least I think.

**Comment by milabs** [comment]
Well, `-t` option seems to be used to specify "TCP" and indeed that's what we want. I'll update the example, thank you!

**Comment by milabs** [comment]
BTW, do you use the project? @vspin

**Comment by vspin** [comment]
Yes, and it works GREAT!


-----Original Message-----

**Comment by milabs** [comment]
> Yes, and it works GREAT!
awesome!
cc: @vspin
